name: Deploy to S3

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install  # Adjust for your project (use yarn or pnpm if needed)
          npm run build  # This should output files to 'dist' or 'build' folder

      - name: Deploy to S3
        uses: aws-actions/s3-sync-action@main
        with:
          bucket: zhaojunan.com
          region: us-east-1  # Change to your bucket’s region
          source-dir: build  # Change if your build output is different
          delete: true  # Deletes removed files from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront Cache (Optional)
        run: |
          aws cloudfront create-invalidation --distribution-id E3A06VEUCFV1VQ --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}